version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    reviewers:
      - kelp404
    commit-message:
      prefix: chore
