version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node10
      - node12
jobs:
  node10:
    working_directory: ~/kue-admin-panel
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: npm install
      - run: npm eslint

  node12:
    working_directory: ~/kue-admin-panel
    docker:
      - image: node:12.3.1
    steps:
      - checkout
      - run: npm install
      - run: npm eslint
