version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node12
jobs:
  node12:
    working_directory: ~/kue-admin-panel
    docker:
      - image: node:12.8.1
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
