name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        redis-version: [4, 5, 6]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}
      - run: npm install
      - run: npm run eslint
      - run: npm test
      - run: npm run build
